version: '3.4'
services:
  airline_db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airline
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - airline_db:/var/lib/mysql
volumes:
  airline_db: { }